// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cuskxtsajbfeiahdlutu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1c2t4dHNhamJmZWlhaGRsdXR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMDcwMzgsImV4cCI6MjA2NDY4MzAzOH0.YHA5a4HOGy-C6ULotJp3-EefLguX0mfrhuuzPVFoXMM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);